# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sms.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(573, 302)
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(11, 21, 74, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(273, 21, 41, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(386, 250, 141, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit_1 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_1.setGeometry(QtCore.QRect(11, 46, 256, 192))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_1.setFont(font)
        self.plainTextEdit_1.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(273, 46, 256, 192))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_1.setText(_translate("Form", "Абоненты"))
        self.label_2.setText(_translate("Form", "Текст"))
        self.pushButton.setText(_translate("Form", "Отправить"))
        self.plainTextEdit_1.setPlainText(_translate("Form", "+79678001714\n"
"+79678001767"))
        self.plainTextEdit_2.setPlainText(_translate("Form", "Test SMS"))
